version: '3.8'

services:
  dev:
    container_name: nestjs_api_dev
    image: test-task-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
    networks:
      - test-task-network
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: nestjs_api_prod
    image: test-task-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
    networks:
      - test-task-network
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    restart: unless-stopped

networks:
  test-task-network:
